services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=9mayra
      - MONGO_INITDB_ROOT_PASSWORD=9mayra2025

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 9mayra
      ME_CONFIG_MONGODB_ADMINPASSWORD: 9mayra2025
      ME_CONFIG_MONGODB_URL: mongodb://9mayra:9mayra2025@mongodb:27017/9mayra?authSource=admin
      ME_CONFIG_BASICAUTH: false

volumes:
  mongodb_data:
